language: java

install:
  - chmod a+rx .travis/*.sh
  - .travis/setup-environment.sh
  - .travis/setup-mavenrc.sh

script:
  - mvn clean install

env:
  global:
    - REQUIRED_JAVA_RUNTIMES="oracle-jdk-1.8.0_40,oracle-server-jre-1.8.0_45,oracle-jre-1.8.0_45,oracle-jre-1.7.0_80,azul-zulu-1.8.0_45,azul-zulu-1.7.0_80"
    - REQUIRED_MAVEN_VERSIONS="3.3.3"
    - MAVEN_HOME=$HOME/bin/apache-maven-3.3.3
    - PATH=$MAVEN_HOME/bin:$PATH
  matrix:    
    - JAVA_HOME=$HOME/bin/oracle-jdk-1.8.0_40 TESTAPP_JAVA_HOME=$HOME/bin/oracle-jdk-1.8.0_40        PATH=$JAVA_HOME/bin:$PATH
    - JAVA_HOME=$HOME/bin/oracle-jdk-1.8.0_40 TESTAPP_JAVA_HOME=$HOME/bin/oracle-server-jre-1.8.0_45 PATH=$JAVA_HOME/bin:$PATH
    - JAVA_HOME=$HOME/bin/oracle-jdk-1.8.0_40 TESTAPP_JAVA_HOME=$HOME/bin/oracle-jre-1.8.0_45        PATH=$JAVA_HOME/bin:$PATH
    - JAVA_HOME=$HOME/bin/oracle-jdk-1.8.0_40 TESTAPP_JAVA_HOME=$HOME/bin/oracle-jre-1.7.0_80        PATH=$JAVA_HOME/bin:$PATH
    - JAVA_HOME=$HOME/bin/oracle-jdk-1.8.0_40 TESTAPP_JAVA_HOME=$HOME/bin/azul-zulu-1.8.0_45         PATH=$JAVA_HOME/bin:$PATH
    - JAVA_HOME=$HOME/bin/oracle-jdk-1.8.0_40 TESTAPP_JAVA_HOME=$HOME/bin/azul-zulu-1.7.0_80         PATH=$JAVA_HOME/bin:$PATH
    
    - JAVA_HOME=$HOME/bin/oracle-server-jre-1.8.0_45 TESTAPP_JAVA_HOME=$HOME/bin/oracle-jdk-1.8.0_40        PATH=$JAVA_HOME/bin:$PATH
    - JAVA_HOME=$HOME/bin/oracle-server-jre-1.8.0_45 TESTAPP_JAVA_HOME=$HOME/bin/oracle-server-jre-1.8.0_45 PATH=$JAVA_HOME/bin:$PATH
    - JAVA_HOME=$HOME/bin/oracle-server-jre-1.8.0_45 TESTAPP_JAVA_HOME=$HOME/bin/oracle-jre-1.8.0_45        PATH=$JAVA_HOME/bin:$PATH
    - JAVA_HOME=$HOME/bin/oracle-server-jre-1.8.0_45 TESTAPP_JAVA_HOME=$HOME/bin/oracle-jre-1.7.0_80        PATH=$JAVA_HOME/bin:$PATH
    - JAVA_HOME=$HOME/bin/oracle-server-jre-1.8.0_45 TESTAPP_JAVA_HOME=$HOME/bin/azul-zulu-1.8.0_45         PATH=$JAVA_HOME/bin:$PATH
    - JAVA_HOME=$HOME/bin/oracle-server-jre-1.8.0_45 TESTAPP_JAVA_HOME=$HOME/bin/azul-zulu-1.7.0_80         PATH=$JAVA_HOME/bin:$PATH
    
    - JAVA_HOME=$HOME/bin/azul-zulu-1.8.0_45 TESTAPP_JAVA_HOME=$HOME/bin/oracle-jdk-1.8.0_40        PATH=$JAVA_HOME/bin:$PATH
    - JAVA_HOME=$HOME/bin/azul-zulu-1.8.0_45 TESTAPP_JAVA_HOME=$HOME/bin/oracle-server-jre-1.8.0_45 PATH=$JAVA_HOME/bin:$PATH
    - JAVA_HOME=$HOME/bin/azul-zulu-1.8.0_45 TESTAPP_JAVA_HOME=$HOME/bin/oracle-jre-1.8.0_45        PATH=$JAVA_HOME/bin:$PATH
    - JAVA_HOME=$HOME/bin/azul-zulu-1.8.0_45 TESTAPP_JAVA_HOME=$HOME/bin/oracle-jre-1.7.0_80        PATH=$JAVA_HOME/bin:$PATH
    - JAVA_HOME=$HOME/bin/azul-zulu-1.8.0_45 TESTAPP_JAVA_HOME=$HOME/bin/azul-zulu-1.8.0_45         PATH=$JAVA_HOME/bin:$PATH
    - JAVA_HOME=$HOME/bin/azul-zulu-1.8.0_45 TESTAPP_JAVA_HOME=$HOME/bin/azul-zulu-1.7.0_80         PATH=$JAVA_HOME/bin:$PATH
  
cache:
  directories:
  - $HOME/bin
  - $HOME/.m2
