sudo: false
language: java

install:
  - chmod a+rx .travis/*.sh
  - .travis/setup-environment.sh
  - .travis/setup-mavenrc.sh

script:
  - $MAVEN_HOME/bin/mvn clean install

env:
  global:
    - REQUIRED_JAVA_RUNTIMES="oracle-jdk-1.8.0_131,oracle-server-jre-1.8.0_131,oracle-jre-1.8.0_131,oracle-jre-1.7.0_80,azul-zulu-8.0.112,azul-zulu-7.0.121"
    - REQUIRED_MAVEN_VERSIONS="3.5.0"
    - MAVEN_HOME=$HOME/bin/apache-maven-3.5.0
    - MAVEN_HOME=$HOME/bin/apache-maven-3.5.0
    - PATH=$MAVEN_HOME/bin:$PATH
  matrix:
    - JAVA_HOME=$HOME/bin/oracle-jdk-1.8.0_131 TESTAPP_JAVA_HOME=$HOME/bin/oracle-jdk-1.8.0_131        PATH=$JAVA_HOME/bin:$PATH
    - JAVA_HOME=$HOME/bin/oracle-jdk-1.8.0_131 TESTAPP_JAVA_HOME=$HOME/bin/oracle-server-jre-1.8.0_131 PATH=$JAVA_HOME/bin:$PATH
    - JAVA_HOME=$HOME/bin/oracle-jdk-1.8.0_131 TESTAPP_JAVA_HOME=$HOME/bin/oracle-jre-1.8.0_131        PATH=$JAVA_HOME/bin:$PATH
    - JAVA_HOME=$HOME/bin/oracle-jdk-1.8.0_131 TESTAPP_JAVA_HOME=$HOME/bin/oracle-jre-1.7.0_80         PATH=$JAVA_HOME/bin:$PATH
    - JAVA_HOME=$HOME/bin/oracle-jdk-1.8.0_131 TESTAPP_JAVA_HOME=$HOME/bin/azul-zulu-8.0.112           PATH=$JAVA_HOME/bin:$PATH
    - JAVA_HOME=$HOME/bin/oracle-jdk-1.8.0_131 TESTAPP_JAVA_HOME=$HOME/bin/azul-zulu-7.0.121           PATH=$JAVA_HOME/bin:$PATH

    - JAVA_HOME=$HOME/bin/oracle-server-jre-1.8.0_131 TESTAPP_JAVA_HOME=$HOME/bin/oracle-jdk-1.8.0_131        PATH=$JAVA_HOME/bin:$PATH
    - JAVA_HOME=$HOME/bin/oracle-server-jre-1.8.0_131 TESTAPP_JAVA_HOME=$HOME/bin/oracle-server-jre-1.8.0_131 PATH=$JAVA_HOME/bin:$PATH
    - JAVA_HOME=$HOME/bin/oracle-server-jre-1.8.0_131 TESTAPP_JAVA_HOME=$HOME/bin/oracle-jre-1.8.0_131        PATH=$JAVA_HOME/bin:$PATH
    - JAVA_HOME=$HOME/bin/oracle-server-jre-1.8.0_131 TESTAPP_JAVA_HOME=$HOME/bin/oracle-jre-1.7.0_80         PATH=$JAVA_HOME/bin:$PATH
    - JAVA_HOME=$HOME/bin/oracle-server-jre-1.8.0_131 TESTAPP_JAVA_HOME=$HOME/bin/azul-zulu-8.0.112           PATH=$JAVA_HOME/bin:$PATH
    - JAVA_HOME=$HOME/bin/oracle-server-jre-1.8.0_131 TESTAPP_JAVA_HOME=$HOME/bin/azul-zulu-7.0.121           PATH=$JAVA_HOME/bin:$PATH

    - JAVA_HOME=$HOME/bin/azul-zulu-8.0.112 TESTAPP_JAVA_HOME=$HOME/bin/oracle-jdk-1.8.0_131        PATH=$JAVA_HOME/bin:$PATH
    - JAVA_HOME=$HOME/bin/azul-zulu-8.0.112 TESTAPP_JAVA_HOME=$HOME/bin/oracle-server-jre-1.8.0_131 PATH=$JAVA_HOME/bin:$PATH
    - JAVA_HOME=$HOME/bin/azul-zulu-8.0.112 TESTAPP_JAVA_HOME=$HOME/bin/oracle-jre-1.8.0_131        PATH=$JAVA_HOME/bin:$PATH
    - JAVA_HOME=$HOME/bin/azul-zulu-8.0.112 TESTAPP_JAVA_HOME=$HOME/bin/oracle-jre-1.7.0_80         PATH=$JAVA_HOME/bin:$PATH
    - JAVA_HOME=$HOME/bin/azul-zulu-8.0.112 TESTAPP_JAVA_HOME=$HOME/bin/azul-zulu-8.0.112           PATH=$JAVA_HOME/bin:$PATH
    - JAVA_HOME=$HOME/bin/azul-zulu-8.0.112 TESTAPP_JAVA_HOME=$HOME/bin/azul-zulu-7.0.121           PATH=$JAVA_HOME/bin:$PATH

cache:
  directories:
    - $HOME/download
    - $HOME/.m2
