sudo: false
language: java

install:
  - chmod a+rx .travis/*.sh
  - .travis/setup-environment.sh
  - .travis/setup-mavenrc.sh

script:
  - $MAVEN_HOME/bin/mvn clean install

env:
  global:
    - REQUIRED_JAVA_RUNTIMES="oracle-jdk-1.8.0_51,oracle-server-jre-1.8.0_51,oracle-jre-1.8.0_51,oracle-jre-1.7.0_80,azul-zulu-1.8.0_51,azul-zulu-1.7.0_85"
    - REQUIRED_MAVEN_VERSIONS="3.3.3"
    - MAVEN_HOME=$HOME/bin/apache-maven-3.3.3
    - PATH=$MAVEN_HOME/bin:$PATH
  matrix:    
    - JAVA_HOME=$HOME/bin/oracle-jdk-1.8.0_51 TESTAPP_JAVA_HOME=$HOME/bin/oracle-jdk-1.8.0_51        PATH=$JAVA_HOME/bin:$PATH
    - JAVA_HOME=$HOME/bin/oracle-jdk-1.8.0_51 TESTAPP_JAVA_HOME=$HOME/bin/oracle-server-jre-1.8.0_51 PATH=$JAVA_HOME/bin:$PATH
    - JAVA_HOME=$HOME/bin/oracle-jdk-1.8.0_51 TESTAPP_JAVA_HOME=$HOME/bin/oracle-jre-1.8.0_51        PATH=$JAVA_HOME/bin:$PATH
    - JAVA_HOME=$HOME/bin/oracle-jdk-1.8.0_51 TESTAPP_JAVA_HOME=$HOME/bin/oracle-jre-1.7.0_80        PATH=$JAVA_HOME/bin:$PATH
    - JAVA_HOME=$HOME/bin/oracle-jdk-1.8.0_51 TESTAPP_JAVA_HOME=$HOME/bin/azul-zulu-1.8.0_51         PATH=$JAVA_HOME/bin:$PATH
    - JAVA_HOME=$HOME/bin/oracle-jdk-1.8.0_51 TESTAPP_JAVA_HOME=$HOME/bin/azul-zulu-1.7.0_85         PATH=$JAVA_HOME/bin:$PATH
    
    - JAVA_HOME=$HOME/bin/oracle-server-jre-1.8.0_51 TESTAPP_JAVA_HOME=$HOME/bin/oracle-jdk-1.8.0_51        PATH=$JAVA_HOME/bin:$PATH
    - JAVA_HOME=$HOME/bin/oracle-server-jre-1.8.0_51 TESTAPP_JAVA_HOME=$HOME/bin/oracle-server-jre-1.8.0_51 PATH=$JAVA_HOME/bin:$PATH
    - JAVA_HOME=$HOME/bin/oracle-server-jre-1.8.0_51 TESTAPP_JAVA_HOME=$HOME/bin/oracle-jre-1.8.0_51        PATH=$JAVA_HOME/bin:$PATH
    - JAVA_HOME=$HOME/bin/oracle-server-jre-1.8.0_51 TESTAPP_JAVA_HOME=$HOME/bin/oracle-jre-1.7.0_80        PATH=$JAVA_HOME/bin:$PATH
    - JAVA_HOME=$HOME/bin/oracle-server-jre-1.8.0_51 TESTAPP_JAVA_HOME=$HOME/bin/azul-zulu-1.8.0_51         PATH=$JAVA_HOME/bin:$PATH
    - JAVA_HOME=$HOME/bin/oracle-server-jre-1.8.0_51 TESTAPP_JAVA_HOME=$HOME/bin/azul-zulu-1.7.0_85         PATH=$JAVA_HOME/bin:$PATH
    
    - JAVA_HOME=$HOME/bin/azul-zulu-1.8.0_51 TESTAPP_JAVA_HOME=$HOME/bin/oracle-jdk-1.8.0_51        PATH=$JAVA_HOME/bin:$PATH
    - JAVA_HOME=$HOME/bin/azul-zulu-1.8.0_51 TESTAPP_JAVA_HOME=$HOME/bin/oracle-server-jre-1.8.0_51 PATH=$JAVA_HOME/bin:$PATH
    - JAVA_HOME=$HOME/bin/azul-zulu-1.8.0_51 TESTAPP_JAVA_HOME=$HOME/bin/oracle-jre-1.8.0_51        PATH=$JAVA_HOME/bin:$PATH
    - JAVA_HOME=$HOME/bin/azul-zulu-1.8.0_51 TESTAPP_JAVA_HOME=$HOME/bin/oracle-jre-1.7.0_80        PATH=$JAVA_HOME/bin:$PATH
    - JAVA_HOME=$HOME/bin/azul-zulu-1.8.0_51 TESTAPP_JAVA_HOME=$HOME/bin/azul-zulu-1.8.0_51         PATH=$JAVA_HOME/bin:$PATH
    - JAVA_HOME=$HOME/bin/azul-zulu-1.8.0_51 TESTAPP_JAVA_HOME=$HOME/bin/azul-zulu-1.7.0_85         PATH=$JAVA_HOME/bin:$PATH

cache:
  directories:
    - $HOME/download
    - $HOME/.m2
